apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: invoice-build-deployer
  namespace: invoice-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-deployer
subjects:
- kind: ServiceAccount
  name: github
  namespace: default
